### PR TITLE
Fix episode 14 easter egg (#162)

### LINKED ISSUE #162: Fix S02E07 easter egg
Looks like the image directory refactor didn't make it to the JS for this page.

Should be an easy fix - just replace `14` with `S02E07` in [episode14.js](https://github.com/mozilla/irlpodcast/blob/master/src/js/episode14.js#L11-L12).

### PR DESCRIPTION
**Pull request by stephaniehobson**
Fix #162

### CODE REVIEW

**Comment by jpetto** [comment]
Sigh, my bad for poor issue reporting. Should be replacing the path to the image _in_ the JS file itself, not changing the name of the JS file.

https://github.com/mozilla/irlpodcast/blob/master/src/js/episode14.js#L11-L12

**Comment by stephaniehobson** [comment]
updated 😣

**Comment by jpetto** [comment]
Don't need to rename the file though 😕. (I _think_ the rename is causing the merge conflict.)

**Comment by stephaniehobson** [comment]
Serves me right for dashing it off before my morning tea. 🍵

**Pull request merged**
